name: Build Go binaries

on: 
  push:
    tags:
      - "v*"


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Make binaries
        uses: xxxserxxx/actions/golang-build@master
        with:
          args: darwin/amd64/1 linux/amd64 linux/386 linux/arm64 linux/arm7 linux/arm6 linux/arm5 windows/amd64 windows/386 freebsd/amd64 freebsd/386
        env:
          COMPRESS_FILES: true

      - name: Pre-release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ GITHUB_REF }}"
          draft: true
          title: "Release candidate"
          files: |
            .release/*.tgz
            .release/*.zip
